name: Docker image build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERTOKEN }} | docker login -u "manuav007" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t manuav007/fastapi-docker-cd:latest .
          docker push manuav007/fastapi-docker-cd:latest
